export const GET_RECORDS_REQUEST = 'GET_RECORDS_REQUEST';
export const GET_RECORD_REQUEST = 'GET_RECORD_REQUEST';
export const CREATE_RECORD_REQUEST = 'CREATE_RECORD_REQUEST';
export const UPDATE_RECORD_REQUEST = 'UPDATE_RECORD_REQUEST';
export const SET_RECORD = 'SET_RECORD';

export const GET_RECORD_TYPES_REQUEST = 'GET_RECORD_TYPES_REQUEST';
export const GET_RECORD_TYPE_REQUEST = 'GET_RECORD_TYPE_REQUEST';
export const CREATE_RECORD_TYPE_REQUEST = 'CREATE_RECORD_TYPE_REQUEST';
export const UPDATE_RECORD_TYPE_REQUEST = 'UPDATE_RECORD_TYPE_REQUEST';
export const DELETE_RECORD_TYPE_REQUEST = 'DELETE_RECORD_TYPE_REQUEST';
export const SET_RECORD_TYPE = 'SET_RECORD_TYPE';
